// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  Translation: {
    title: "Hi, Welcome Domique Fusion";
    content: "Here, we serve you the best food and quality service.";
    notFound: "Sorry, Page Not Found";
    authorize: "Sorry, You Need Login To Access";
    returnHome: "Return To Home";
    returnLogin: "Return To Login";
    login: {
      titleLogin: "Sign in to your account";
      dontHaveAccount: "Don’t have an account?";
      forgotPassword: "Forgot password?";
      continueWith: "or continue with";
      password: "Password";
      validate: {
        email: "Email is required!";
        invalidEmail: "Invalid email!";
        password: "Password is required!";
      };
    };
    register: {
      alreadyHaveAnAccount: "Already have an account?";
      titleRegister: "Get started absolutely free";
      firstName: "First Name";
      lastName: "Last Name";
      dateOfBirth: "Date Of Birth";
      numberPhone: "Number Phone";
      address: "Address";
      password: "Password";
      confirmPassword: "Confirm Password";
      createAccount: "Create account";
      validate: {
        email: "Email is required!";
        invalidEmail: "Invalid email!";
        password: "Password is required!";
        minPassword: "Password must be at least 8 characters!";
        maxPassword: "Password must be max 20 characters!";
        formatPassword: "Password must have at least 8 characters, one uppercase, one lowercase, one number, and one special character.";
        firstName: "First name is required!";
        minFirstName: "First name must be at least 3 characters";
        maxFirstName: "First name must max 50 characters";
        lastName: "Last name is required!";
        minLastName: "Last name must be at least 3 characters";
        maxLastName: "Last name must max 50 characters";
        dateOfBirth: "Date of birth is required!";
        numberPhone: "Number phone is required!";
        minNumberPhone: "Phone number must be at least 10 digits";
        maxNumberPhone: "Phone number must be max 50 digits";
        address: "Address is required!";
        minAddress: "Address must be at least 5 characters";
        maxAddress: "Address must not exceed 100 characters";
        confirmPassword: "Confirm password is required!";
        matchPassword: "Password must match";
        ageRequirement: "You must be at least 13 years old!";
      };
    };
    forgotPassword: {
      title: "Forgot your password?";
      content: "Please enter the email address associated with your account and we'll email you a link to reset your password.";
      button: "Send request";
      return: "Return to sign in";
    };
    resetPassword: {
      title: "Request sent successfully";
      content: "We've sent a 6-digit confirmation email to your email. Please enter the code in below box to verify your email.";
      password: "Password";
      confirmPassword: "Confirm Password";
      updatePassword: "Update password";
      dontHaveACode: "Don’t have a code?";
      return: "Return to sign in";
      verify: "Verify";
      validate: {
        password: "Password is required!";
        minPassword: "Password must be at least 8 characters!";
        maxPassword: "Password must be max 20 characters!";
        formatPassword: "Password must have at least 8 characters, one uppercase, one lowercase, one number, and one special character.";
        confirmPassword: "Confirm password is required!";
        matchPassword: "Password must match";
      };
      resend: "Resend";
    };
    button: {
      signIn: "Sign in";
      signUp: "Sign up";
      back: "Back";
      next: "Next";
      submit: "Submit";
      cancel: "Cancel";
      detail: "Detail";
      verify: "Verify";
      getStarted: "Get started";
      confirm: "Confirm";
    };
    navbar: {
      home: "Home";
      about: "About Domique Fusion";
      concepts: "Concepts";
      blog: "Blog";
      yourProfile: "Your Profile";
      reservationHistory: "Reservation History";
      favorites: "Favorites";
      settings: "Settings";
      signOut: "Sign Out";
      login: "Login";
      item: "{item, select, home {Home} about {About Domique Fusion} concepts {Concepts} blog {Blog} yourProfile {Your Profile} reservationHistory {Reservation History} favorites {Favorites} settings {Settings} signOut {Sign Out} login {Login} other {Unknown}}";
    };
    footer: {
      title: "Domique Fusion Corporation";
      address: "Address: Thong Nhat Street, Go Vap Distric, Ho Chi Minh City";
      responsible: "Responsible for content: Mr.Dom Nguyen";
      customerSupport: "Customer Support";
      termsOfUse: "Terms of Use";
      membershipPolicy: "Membership policy";
      privacyPolicy: "Privacy policy";
      copyright: "© {currentYear} Domique Fusion.,JSC. All rights reserved.";
    };
    settings: {
      title: "Settings";
      themeMode: "Theme Mode";
      light: "Light";
      dark: "Dark";
      english: "English";
      vietnamese: "Vietnamese";
      language: "{lng, select, english {English} vietnamese {Vietnamese} other {Unknown}}";
    };
    headTitle: {
      login: "Domique Fusion | Login";
      register: "Domique Fusion | Register";
      about: "Domique Fusion | About";
      home: "Domique Fusion | Home";
      resetPassword: "Domique Fusion | Reset Password";
      forgotPassword: "Domique Fusion | Forgot Password";
      verifyOtp: "Domique Fusion | Verify OTP";
      profile: "Domique Fusion | Profile";
      concepts: "Domique Fusion | Concepts";
      concept: "Domique Fusion | {concept}";
      navbar: "Domique Fusion | {concept} - {navbar}";
      favoriteConcepts: "Domique Fusion | Favorite Concepts";
      favoriteRestaurants: "Domique Fusion | Favorite Restaurants";
      checkInRestaurants: "Domique Fusion | Check In Restaurants";
      menuRestaurant: "Domique Fusion | Menu";
      bookingRestaurant: "Domique Fusion | Booking";
      blog: "Domique Fusion | Blog";
      historyBooking: "Domique Fusion | History Booking";
      notifications: "Domique Fusion | Notifications";
      unauthorized: "Domique Fusion | Unauthorized";
    };
  };
  Home: {
    concept: "Concept";
    contentConcept: "40+ Concepts";
    restaurant: "Restaurant";
    contentRestaurant: "500+ Restaurants";
    location: "Location";
    contentLocation: "42 Province";
    amountVisits: "Amount of visits in 2024";
    contentAmount: "18 million";
    loyalCustomer: "Loyal customer";
    contentLoyalCustomer: "Over 1,600,000";
    partners: "Partners";
    title: "{title, select, concept {Concept} restaurant {Restaurant} location {Location} amountVisits {Amount of visits in 2024} loyalCustomer {Loyal customer} partners {Partners} other {Unknown}}";
    content: "{content, select, contentConcept {40+ Concepts} contentRestaurant {500+ Restaurants} contentLocation {42 Province} contentAmount {18 million} contentLoyalCustomer {Over 1,600,000} contentPartners {With 118 organizations and companies} other {Unknown}}";
    contentPartners: "With 118 organizations and companies";
    about: {
      title: "About Domique Fusion";
      content: "Domique Fusion brings together the finest culinary traditions from around the world. Established in 2025, we pride ourselves on authentic flavors and exceptional service.";
      ourStory: "Our Story";
      contentStory: "Founded in 2010 by Chef Michael Lee, EasyLang Restaurant began as a small family business with a big dream – to create a dining experience that celebrates culinary diversity while maintaining the highest standards of quality and sustainability.";
      contentStory1: "Over the years, we've grown from a modest establishment to one of the most beloved restaurants in the area, earning multiple awards and the loyalty of our wonderful customers who have become like family to us.";
      weOffer: "What We Offer";
      offerTitle1: "Quality Food";
      contentOffer1: "Every dish is carefully crafted using premium ingredients to ensure exceptional taste and presentation.";
      offerTitle2: "Sustainability";
      contentOffer2: "We partner with local farmers and suppliers who share our commitment to sustainable and ethical practices.";
      offerTitle3: "Community";
      contentOffer3: "More than just a restaurant, we strive to be a gathering place where memories are made and communities come together.";
      offers: "{offers, select, offerTitle1 {Quality Food} offerTitle2 {Sustainability} offerTitle3 {Community} other {Unknown}}";
      contentOffers: "{contentOffers, select, contentOffer1 {Every dish is carefully crafted using premium ingredients to ensure exceptional taste and presentation.} contentOffer2 {We partner with local farmers and suppliers who share our commitment to sustainable and ethical practices.} contentOffer3 {More than just a restaurant, we strive to be a gathering place where memories are made and communities come together.} other {Unknown}}";
      ourCuisine: "Our Cuisine";
      contentOurCuisine: "We specialize in international fusion dishes made from locally-sourced, organic ingredients. Our menu changes seasonally to ensure the freshest experience.";
      cuisine1: "Signature fusion dishes combining Asian and European techniques";
      cuisine2: "Seasonal tasting menus showcasing local produce";
      cuisine3: "Extensive selection of vegetarian and vegan options";
      openHour: "Opening Hours";
      monFri: "Monday-Friday";
      satSun: "Saturday-Sunday";
      holidays: "Holidays";
      specialHour: "Special hours (check our social media)";
      location: "Location";
      contact: "Contact";
      visitUs: "Visit Us Soon";
      lookingForward: "We look forward to serving you and providing an unforgettable dining experience!";
      reservation: "Make a Reservation";
    };
  };
  Restaurant: {
    concepts: {
      label: {
        allConcepts: "All concepts";
        hotpot: "Hotpot";
        other: "Other";
        japanese: "Japanese";
        steakHouse: "Steak House";
        bbq: "BBQ";
      };
      placeholder: {
        search: "Search";
        notes: "Notes...";
      };
    };
    label: {
      date: "Meal day";
      time: "Meal time";
      peopleQuantity: "Quantity of people";
      fullName: "Full name";
      numberPhone: "Number phone";
      notes: "Notes";
    };
    bookingSuccessfully: "Booking completed successfully!";
    notFound: "Oops! We couldn’t find any restaurants :(";
    under: "Under";
    over: "Over";
    from: "From";
    to: "To";
    allPrices: "All prices";
    allStar: "All star";
    openClose: "Open - Close";
    validate: {
      fieldIsRequired: "This field is required!";
    };
    button: {
      booking: "Booking";
    };
  };
  Profile: {
    title: "Profile";
    photoUpdate: "Photo Update";
    allowType: "Allow *.jpeg, *.jpg, *.png, *.gif";
    maxSize: " max size of 3.1MB";
    tabProfile: "Profile";
    tabSecurity: "Security";
    tabs: "{tabs, select, tabProfile {Profile} tabSecurity {Security} other {Unknown}}";
    modal: {
      delete: {
        button: "Delete";
        title: "Delete Account";
        content: "Are you sure you want to delete your account? All of your data will be permanently removed. This action cannot be undone.";
        labelButton: "Cancel";
      };
      update: {
        title: "Update Account";
        button: "Update";
        labelButton: "Cancel";
        content: "Are you sure update your profile?";
      };
    };
    profile: {
      firstName: "First Name";
      lastName: "Last Name";
      address: "Address";
      gender: "Gender";
      numberPhone: "Number Phone";
      dateOfBirth: "Date Of Birth";
      button: "Update Account";
      male: "Male";
      female: "Female";
      typeOfGender: "{gender, select, male {Male} female {Female} other {Unknown}}";
      validate: {
        firstName: "Please enter your first name!";
        minFirstName: "First name must be at least 3 characters";
        maxFirstName: "First name must not exceed 50 characters";
        lastName: "Please enter your last name!";
        minLastName: "Last name must be at least 3 characters";
        maxLastName: "Last name must not exceed 50 characters";
        numberPhone: "Number Phone is required!";
        minNumberPhone: "Phone number must be at least 10 digits";
        maxNumberPhone: "Phone number must not exceed 15 digits";
        address: "Address is required!";
        minAddress: "Address must be at least 5 characters";
        maxAddress: "Address must not exceed 100 characters";
        dateOfBirth: "Date of birth is required!";
        ageRequirement: "You must be at least 13 years old!";
      };
    };
    security: {
      currentPassword: "Current Password";
      newPassword: "New Password";
      confirmPassword: "Confirm Password";
      save: "Save changes";
      validate: {
        currentPassword: "Password is required!";
        minPassword: "Password must be at least 8 characters!";
        maxPassword: "Password must be max 20 characters!";
        formatPassword: "Password must have at least 8 characters, one uppercase, one lowercase, one number, and one special character.";
        newPassword: "New password is required!";
        confirmPassword: "Confirm password is required!";
        matchPassword: "Password must match";
      };
    };
  };
  Notification: {
    noNotifications: "No notifications";
    seeMore: "See more";
    content: {
      bookingCreated: {
        detail: {
          hi: "Hi";
          content_1: "You have successfully booked a table at the restaurant of";
          content_2: "at the time";
          content_3: "for";
          content_4: "people.";
          content_5: "Please wait for the restaurant to confirm. You will receive a notification when there is a response from the restaurant.";
          content_6: "Thank you for using our service!";
        };
      };
      bookingConfirmed: {
        detail: {
          content_1: "The restaurant of";
          content_2: "confirmed your reservation at";
          content_3: "Please arrive on time and present your confirmation code (if available) upon arrival at the restaurant.";
          content_4: "Enjoy your meal!";
        };
      };
      bookingCanceled: {
        detail: {
          content_1: "Sorry, the restaurant of";
          content_2: "refused to reserve your table at";
          content_3: "The reason could be that the restaurant is full or unable to serve at that time.";
          content_4: "You can try rebooking with a different time or choose a different restaurant.";
          content_5: "We apologize for any inconvenience.";
        };
      };
      bookingReminder: {
        detail: {
          content_1: "You have a table reservation at";
          content_2: "Please arrive on time for the best service. If you cannot come, please cancel your reservation early to avoid affecting the restaurant.";
          content_3: "Thank you for trusting and using our services!";
        };
      };
      bookingCompleted: {
        detail: {
          content_1: "We hope you had a wonderful dining experience at";
          content_2: "Your reservation on";
          content_3: "has been marked as completed.";
          content_4: "Thank you for choosing us! If you enjoyed your meal, we’d love to hear your feedback.";
          content_5: "We look forward to welcoming you again soon.";
          content_6: "Leave a review";
          content_7: "people";
        };
      };
      bookingInProgress: {
        detail: {
          content_1: "We hope you are enjoying your dining experience at";
          content_2: "is currently in progress.";
          content_3: "Thank you for choosing us! If you need any assistance, please don’t hesitate to ask.";
          content_4: "We look forward to serving you and welcoming you again soon.";
        };
      };
    };
    infoRestaurant: "Restaurant information:";
  };
  Concept: {
    title: "My Favorite List";
    titleCheckIn: "My Check in List";
    titleRestaurantFavorite: "Restaurants I Love";
    emptyListTitle: "Your list is empty";
    emptyContent: "You have no favorites yet";
    checkinEmptyContent: "You have no visited restaurants yet";
    touchTheHeartIcon: "Touch the Heart icon on any";
    touchTheVisitIcon: "Touch the Visited icon on any";
    andItWill: "and it will save them here as a favorite.";
    andItWillVisited: "and it will save them here as a visited.";
    restaurant: "restaurant";
    visited: "Visited";
    allDone: "All done!";
    thankForSharing: "Thanks for sharing your feedback with us.";
    pleaseShare: "Please share your experience.";
    howWasTheRestaurant: "How was the restaurant&apos;s service & cooking?";
    terrible: "1 - Terrible";
    amazing: "5 - Amazing";
    pleaseShareAnyAdditional: "Please share any additional comments about this concept:";
    placehoderTextarea: "Write your thoughts here...";
    seeMenu: "See menu";
    validateReview: "Please enter least 5 characters !";
    notFound: "Oops! We couldn’t find any restaurants :(";
    navbar: "{navbar, select, menu {Menu} booking {Booking} other {Unknown}}";
    button: {
      back: "My lists";
      submit: "Submit";
      close: "Close";
      goBack: "Back";
    };
  };
  Booking: {
    title: "Reservation History";
    noBooking: "You have not booked any restaurant table yet. :(";
    contentNoBooking: "to experience the delicious cuisine at our restaurant!";
    modal: {
      delete: {
        button: "Canceled Reservation";
        title: "Canceled Reservation";
        content: "Are you sure you want to canceled your reservation?";
        labelButton: "Cancel";
      };
    };
    notification: {
      canceled: "Your reservation has been canceled successfully.";
    };
    status: "{status, select, pending {Pending} confirmed {Confirmed} cancelled {Cancelled} completed {Completed} inProgress {In Progress} other {Unknown}}";
    note: "Special requirements:";
    thankYou: "Thank you for visiting Domique Fusion!";
    reservationCode: "Reservation code:";
    button: {
      bookingAgain: "Booking Again";
      goBack: "Back";
      contact: "Contact Restaurant";
      bookingNow: "[ Booking Now ]";
    };
    statusLabel: {
      pending: "Booking waiting for confirmation";
      confirmed: "Reservation confirmed";
      cancelled: "Reservation cancelled";
      completed: "The meal is completed";
      inProgress: "The meal is in progress";
    };
  };
};
export default messages;
